package Forms;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author isaaxh
 */
import java.awt.event.ActionEvent;
import java.lang.reflect.Array;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.UUID;

import javax.swing.table.DefaultTableModel;
import HelperClasses.AllCars;
import HelperClasses.AllCustomers;
import HelperClasses.AllRentals;
import HelperClasses.Car;
import HelperClasses.Customer;
import HelperClasses.Rental;

public class AdminRentalPage extends javax.swing.JFrame {

        public AdminRentalPage() {
                initComponents();
                addCarDataToTable();
                addRentalDataToTable();
                setCustomerIdCombo();
                setCarIdCombo();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                jMenuItem1 = new javax.swing.JMenuItem();
                jMenu1 = new javax.swing.JMenu();
                jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
                buttonGroup1 = new javax.swing.ButtonGroup();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                backgroundPanel = new javax.swing.JPanel();
                sidebarPanel = new javax.swing.JPanel();
                btnLogout = new javax.swing.JButton();
                labelCustomerID = new javax.swing.JLabel();
                labelRentDate = new javax.swing.JLabel();
                labelReturnDate = new javax.swing.JLabel();
                rentDateEndTextInput = new javax.swing.JTextField();
                rentDateTextInput = new javax.swing.JTextField();
                customerIdCombo = new javax.swing.JComboBox<>();
                labelRentalID1 = new javax.swing.JLabel();
                carIdCombo = new javax.swing.JComboBox<>();
                carRentalTitle = new javax.swing.JLabel();
                btnSave = new javax.swing.JButton();
                btnEdit = new javax.swing.JButton();
                btnReset = new javax.swing.JButton();
                jPanel2 = new javax.swing.JPanel();
                jScrollPane3 = new javax.swing.JScrollPane();
                tableCarsOnRent = new javax.swing.JTable();
                jLabel3 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tableCarList = new javax.swing.JTable();
                jLabel2 = new javax.swing.JLabel();

                jLabel1.setText("jLabel1");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));

                jMenuItem1.setText("jMenuItem1");

                jMenu1.setText("jMenu1");

                jRadioButtonMenuItem1.setSelected(true);
                jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "Title 1", "Title 2", "Title 3", "Title 4"
                                }));
                jScrollPane2.setViewportView(jTable1);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(255, 255, 255));
                setMinimumSize(new java.awt.Dimension(900, 700));
                setName("rentalPage"); // NOI18N

                backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
                backgroundPanel.setPreferredSize(new java.awt.Dimension(850, 328));

                sidebarPanel.setBackground(new java.awt.Color(8, 65, 118));

                btnLogout.setBackground(new java.awt.Color(8, 65, 118));
                btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btnLogout.setForeground(new java.awt.Color(255, 255, 255));
                btnLogout.setText("Log Out");

                labelCustomerID.setBackground(new java.awt.Color(255, 250, 250));
                labelCustomerID.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
                labelCustomerID.setForeground(new java.awt.Color(255, 255, 255));
                labelCustomerID.setText("Customer ID");

                labelRentDate.setBackground(new java.awt.Color(255, 250, 250));
                labelRentDate.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
                labelRentDate.setForeground(new java.awt.Color(255, 255, 255));
                labelRentDate.setText("Rent Start Date");

                labelReturnDate.setBackground(new java.awt.Color(255, 250, 250));
                labelReturnDate.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
                labelReturnDate.setForeground(new java.awt.Color(255, 255, 255));
                labelReturnDate.setText("Return date end");

                rentDateEndTextInput.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rentDateEndTextInputActionPerformed(evt);
                        }

                        private void rentDateEndTextInputActionPerformed(ActionEvent evt) {
                        }
                });

                rentDateTextInput.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rentDateTextInputActionPerformed(evt);
                        }

                        private void rentDateTextInputActionPerformed(ActionEvent evt) {
                        }
                });

                customerIdCombo.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                labelRentalID1.setBackground(new java.awt.Color(255, 250, 250));
                labelRentalID1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
                labelRentalID1.setForeground(new java.awt.Color(255, 255, 255));
                labelRentalID1.setText("Car ID");

                // carIdCombo.setModel(new javax.swing.DefaultComboBoxModel<>(
                // new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                carRentalTitle.setBackground(new java.awt.Color(255, 250, 250));
                carRentalTitle.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
                carRentalTitle.setForeground(new java.awt.Color(255, 255, 255));
                carRentalTitle.setText("Car Rental");

                btnSave.setText("Save");
                btnSave.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSaveActionPerformed(evt);
                        }
                });

                btnEdit.setText("Edit");

                btnReset.setText("Reset");
                btnReset.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnResetActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
                sidebarPanel.setLayout(sidebarPanelLayout);
                sidebarPanelLayout.setHorizontalGroup(
                                sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                sidebarPanelLayout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(carRentalTitle)
                                                                                .addGap(111, 111, 111))
                                                .addGroup(sidebarPanelLayout.createSequentialGroup()
                                                                .addGroup(sidebarPanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(sidebarPanelLayout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                .addGroup(sidebarPanelLayout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGap(35, 35, 35)
                                                                                                                .addGroup(sidebarPanelLayout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(labelRentalID1)
                                                                                                                                .addGroup(sidebarPanelLayout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addGroup(sidebarPanelLayout
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                .addGroup(sidebarPanelLayout
                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                .addComponent(labelCustomerID)
                                                                                                                                                                                .addGap(33, 33, 33))
                                                                                                                                                                .addComponent(labelRentDate,
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                                .addComponent(labelReturnDate,
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING))
                                                                                                                                                .addGap(14, 14, 14)
                                                                                                                                                .addGroup(sidebarPanelLayout
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                .addComponent(customerIdCombo,
                                                                                                                                                                                0,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(rentDateTextInput)
                                                                                                                                                                .addComponent(rentDateEndTextInput)
                                                                                                                                                                .addComponent(carIdCombo,
                                                                                                                                                                                0,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)))))
                                                                                                .addGroup(sidebarPanelLayout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGap(39, 39, 39)
                                                                                                                .addComponent(btnSave,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                100,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                .addComponent(btnEdit,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                100,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                .addComponent(btnReset,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                100,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addGroup(sidebarPanelLayout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(btnLogout)))
                                                                .addContainerGap(46, Short.MAX_VALUE)));
                sidebarPanelLayout.setVerticalGroup(
                                sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(btnLogout)
                                                                .addGap(2, 2, 2)
                                                                .addComponent(carRentalTitle)
                                                                .addGap(70, 70, 70)
                                                                .addGroup(sidebarPanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(carIdCombo,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(labelRentalID1))
                                                                .addGap(10, 10, 10)
                                                                .addGroup(sidebarPanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(customerIdCombo,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(labelCustomerID))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(sidebarPanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(rentDateTextInput,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(labelRentDate))
                                                                .addGap(15, 15, 15)
                                                                .addGroup(sidebarPanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(rentDateEndTextInput,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(labelReturnDate))
                                                                .addGap(44, 44, 44)
                                                                .addGroup(sidebarPanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnSave)
                                                                                .addComponent(btnEdit,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(btnReset,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addGap(591, 591, 591)));

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));
                jPanel2.setPreferredSize(new java.awt.Dimension(529, 259));

                tableCarsOnRent.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null }
                                },
                                new String[] {
                                                "Rent ID", "Car ID", "User ID", "Rent Date", "Return Date"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class,
                                        java.lang.String.class, java.lang.String.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }
                });
                tableCarsOnRent.setGridColor(new java.awt.Color(8, 65, 118));
                jScrollPane3.setViewportView(tableCarsOnRent);
                tableCarsOnRent.getAccessibleContext().setAccessibleName("tableCarsOnRent");

                jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(8, 65, 118));
                jLabel3.setText("Rented Cars");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 504,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel3));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                177,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));

                tableCarList.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
                tableCarList.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null }
                                },
                                new String[] {
                                                "Car ID", "Brand", "Model", "Status", "Price"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.Integer.class, java.lang.String.class, java.lang.String.class,
                                        java.lang.String.class, java.lang.Integer.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }
                });
                tableCarList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                tableCarList.setGridColor(new java.awt.Color(8, 65, 118));
                tableCarList.setMaximumSize(new java.awt.Dimension(600, 72));
                tableCarList.setSelectionBackground(new java.awt.Color(8, 65, 118));
                tableCarList.getTableHeader().setResizingAllowed(false);
                tableCarList.getTableHeader().setReorderingAllowed(false);
                jScrollPane1.setViewportView(tableCarList);
                tableCarList.getAccessibleContext().setAccessibleName("tableCarList");

                jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(8, 65, 118));
                jLabel2.setText("Available Cars");

                javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
                backgroundPanel.setLayout(backgroundPanelLayout);
                backgroundPanelLayout.setHorizontalGroup(
                                backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(backgroundPanelLayout.createSequentialGroup()
                                                                .addComponent(sidebarPanel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(28, 28, 28)
                                                                .addGroup(backgroundPanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jPanel2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                504,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                499,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel2))
                                                                .addContainerGap(202, Short.MAX_VALUE)));
                backgroundPanelLayout.setVerticalGroup(
                                backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(backgroundPanelLayout.createSequentialGroup()
                                                                .addGap(51, 51, 51)
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                179,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(14, 14, 14)
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                227,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                1143,
                                                                Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                526,
                                                                Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        // action button responders
        // ======================================================================================================

        AllCars cars = new AllCars();
        AllCustomers customers = new AllCustomers();
        AllRentals allRentals = new AllRentals();

        private void setCustomerIdCombo() {
                ArrayList<Customer> allCustomers = customers.getAllCustomers();
                int arrSize = allCustomers.size();
                String customerIds[] = new String[arrSize];
                for (int i = 0; i < arrSize; i++) {
                        customerIds[i] = allCustomers.get(i).getId();
                }
                customerIdCombo.setModel(new javax.swing.DefaultComboBoxModel<>(customerIds));
        }

        private void setCarIdCombo() {
                ArrayList<Car> availableCars = cars.getAvailableCars();
                int arrSize = availableCars.size();
                String carIds[] = new String[arrSize];
                System.out.println(arrSize);
                for (int i = 0; i < arrSize; i++) {
                        carIds[i] = availableCars.get(i).getId();
                }
                carIdCombo.setModel(new javax.swing.DefaultComboBoxModel<>(carIds));
        }

        private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveActionPerformed
                String rentalId = UUID.randomUUID().toString();
                String carId = carIdCombo.getSelectedItem().toString();
                String customerId = customerIdCombo.getSelectedItem().toString();
                String rentStartDate = rentDateTextInput.getText();
                String rentEndDate = rentDateEndTextInput.getText();
                String currentDate = LocalDate.now().toString();
                Rental newRental = new Rental(rentalId, carId, customerId, rentStartDate,
                                rentEndDate, currentDate);
                allRentals.addRental(newRental);
                addRentalDataToTable();
        }

        private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {
                resetTextFields();
        }

        private void resetTextFields() {
                rentDateTextInput.setText("");
                rentDateEndTextInput.setText("");
        }

        private void addCarDataToTable() {
                DefaultTableModel carTableModel = (DefaultTableModel) tableCarList.getModel();

                ArrayList<Car> allCars = cars.getAllCars();
                int carArrSize = allCars.size();
                carTableModel.getDataVector().removeAllElements();
                for (int i = 0; i < carArrSize; i++) {
                        Car currCar = allCars.get(i);
                        if (currCar.isAvailable()) {
                                String tableData[] = { currCar.getId(), currCar.getMake(), currCar.getModel(),
                                                currCar.isAvailable() == true ? "Available" : "Booked",
                                                String.valueOf(currCar.getPrice()) };
                                carTableModel.addRow(tableData);
                        }
                }
        }

        private void addRentalDataToTable() {
                DefaultTableModel carsOnRentModel = (DefaultTableModel) tableCarsOnRent.getModel();

                ArrayList<Rental> rentals = allRentals.getAllRental();
                int carArrSize = rentals.size();
                carsOnRentModel.getDataVector().removeAllElements();
                for (int i = 0; i < carArrSize; i++) {
                        Rental currRental = rentals.get(i);
                        String tableData[] = { currRental.getRentalId(), currRental.getCarId(), currRental.getUserId(),
                                        currRental.getStartDate(), currRental.getEndDate()
                        };
                        carsOnRentModel.addRow(tableData);
                }
                resetTextFields();
        }

        public static void main(String args[]) {
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(AdminRentalPage.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(AdminRentalPage.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(AdminRentalPage.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(AdminRentalPage.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new AdminRentalPage().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel backgroundPanel;
        private javax.swing.JButton btnEdit;
        private javax.swing.JButton btnLogout;
        private javax.swing.JButton btnReset;
        private javax.swing.JButton btnSave;
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JComboBox<String> carIdCombo;
        private javax.swing.JLabel carRentalTitle;
        private javax.swing.JComboBox<String> customerIdCombo;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JMenu jMenu1;
        private javax.swing.JMenuItem jMenuItem1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JTable jTable1;
        private javax.swing.JLabel labelCustomerID;
        private javax.swing.JLabel labelRentDate;
        private javax.swing.JLabel labelRentalID1;
        private javax.swing.JLabel labelReturnDate;
        private javax.swing.JTextField rentDateEndTextInput;
        private javax.swing.JTextField rentDateTextInput;
        private javax.swing.JPanel sidebarPanel;
        private javax.swing.JTable tableCarList;
        private javax.swing.JTable tableCarsOnRent;
        // End of variables declaration//GEN-END:variables
}
