package Forms;

import java.util.ArrayList;
import java.util.Date;
import java.util.UUID;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import HelperClasses.AllCars;
import HelperClasses.AllCustomers;
import HelperClasses.AllRentals;
import HelperClasses.Car;
import HelperClasses.Customer;
import HelperClasses.Rental;

public class AdminRentalPage extends CommonFunctionality {

    public AdminRentalPage(Customer aLoggedInCustomer) {
        loggedInCustomer = aLoggedInCustomer;
        initComponents();
        addCarDataToTable();
        addRentalDataToTable();
        setCustomerIdCombo();
        setCarIdCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backgroundPanel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        mainMenuBtn = new javax.swing.JButton();
        labelCustomerID = new javax.swing.JLabel();
        labelRentDate = new javax.swing.JLabel();
        labelReturnDate = new javax.swing.JLabel();
        customerIdCombo = new javax.swing.JComboBox<>();
        labelRentalID1 = new javax.swing.JLabel();
        carIdCombo = new javax.swing.JComboBox<>();
        carRentalTitle = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        rentalStartDate = new com.toedter.calendar.JDateChooser();
        rentalEndDate = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCarsOnRent = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCarList = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(900, 700));
        setName("rentalPage"); // NOI18N

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(850, 328));

        sidebarPanel.setBackground(new java.awt.Color(8, 65, 118));
        sidebarPanel.setMaximumSize(new java.awt.Dimension(250, 30));
        sidebarPanel.setMinimumSize(new java.awt.Dimension(250, 30));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(250, 30));

        mainMenuBtn.setBackground(new java.awt.Color(8, 65, 118));
        mainMenuBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainMenuBtn.setForeground(new java.awt.Color(255, 255, 255));
        mainMenuBtn.setText("Main Menu");

        labelCustomerID.setBackground(new java.awt.Color(255, 250, 250));
        labelCustomerID.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelCustomerID.setForeground(new java.awt.Color(255, 255, 255));
        labelCustomerID.setText("Customer ID");

        labelRentDate.setBackground(new java.awt.Color(255, 250, 250));
        labelRentDate.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelRentDate.setForeground(new java.awt.Color(255, 255, 255));
        labelRentDate.setText("Rent Start Date");

        labelReturnDate.setBackground(new java.awt.Color(255, 250, 250));
        labelReturnDate.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelReturnDate.setForeground(new java.awt.Color(255, 255, 255));
        labelReturnDate.setText("Return date end");

        customerIdCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        customerIdCombo.setMaximumSize(new java.awt.Dimension(250, 30));
        customerIdCombo.setMinimumSize(new java.awt.Dimension(250, 30));
        customerIdCombo.setPreferredSize(new java.awt.Dimension(250, 30));

        labelRentalID1.setBackground(new java.awt.Color(255, 250, 250));
        labelRentalID1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelRentalID1.setForeground(new java.awt.Color(255, 255, 255));
        labelRentalID1.setText("Car ID");

        carIdCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        carIdCombo.setMaximumSize(new java.awt.Dimension(250, 30));
        carIdCombo.setMinimumSize(new java.awt.Dimension(250, 30));
        carIdCombo.setPreferredSize(new java.awt.Dimension(250, 30));

        carRentalTitle.setBackground(new java.awt.Color(255, 250, 250));
        carRentalTitle.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        carRentalTitle.setForeground(new java.awt.Color(255, 255, 255));
        carRentalTitle.setText("Car Rental");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtnActionPerformed(evt);
            }
        });

        tableCarList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCarListMouseClicked(evt);
            }
        });

        rentalStartDate.setMaximumSize(new java.awt.Dimension(250, 30));
        rentalStartDate.setMinimumSize(new java.awt.Dimension(250, 30));
        rentalStartDate.setPreferredSize(new java.awt.Dimension(250, 30));

        rentalEndDate.setMaximumSize(new java.awt.Dimension(250, 30));
        rentalEndDate.setMinimumSize(new java.awt.Dimension(250, 30));
        rentalEndDate.setPreferredSize(new java.awt.Dimension(250, 30));

        Date currDate = new Date();
        rentalStartDate.setDate(currDate);
        rentalEndDate.setDate(currDate);

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRentalID1)
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelReturnDate, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelCustomerID)
                                    .addComponent(labelRentDate))
                                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(customerIdCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(carIdCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rentalEndDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rentalStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                                                .addComponent(mainMenuBtn)
                        .addGap(18, 18, 18)
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(carRentalTitle)
                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        ))
                        .addGap(15, 15, 15))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        ))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(mainMenuBtn)
                                                )
                        .addGap(44, 44, 44)
                        .addComponent(carRentalTitle)
                        .addGap(28, 28, 28)
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRentalID1))
                        .addGap(10, 10, 10)
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCustomerID))
                        .addGap(18, 18, 18)
                        .addComponent(labelRentDate))
                    .addComponent(rentalStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelReturnDate)
                    .addComponent(rentalEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                                )
                .addGap(591, 591, 591))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(529, 259));

        tableCarsOnRent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Rent ID", "Car ID", "User ID", "Rent Date", "Return Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            };
        });
        tableCarsOnRent.setGridColor(new java.awt.Color(8, 65, 118));
        jScrollPane3.setViewportView(tableCarsOnRent);
        tableCarsOnRent.getAccessibleContext().setAccessibleName("tableCarsOnRent");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(8, 65, 118));
        jLabel3.setText("Rented Cars");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tableCarList.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tableCarList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Car ID", "Brand", "Model", "Status", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            };

            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            };
        });
        tableCarList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableCarList.setGridColor(new java.awt.Color(8, 65, 118));
        tableCarList.setMaximumSize(new java.awt.Dimension(600, 72));
        tableCarList.setSelectionBackground(new java.awt.Color(8, 65, 118));
        tableCarList.getTableHeader().setResizingAllowed(false);
        tableCarList.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableCarList);
        tableCarList.getAccessibleContext().setAccessibleName("tableCarList");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(8, 65, 118));
        jLabel2.setText("Available Cars");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, Short.MAX_VALUE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1143, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnEditActionPerformed

    private void mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditActionPerformed
        backToMainMenu();
    }// GEN-LAST:event_btnEditActionPerformed

    private void tableCarListMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_carTableMouseClicked
        // TODO add your handling code here:
        // setting the contained data to the text field
        int SelectedRow = tableCarList.getSelectedRow();
        String RegNum = tableCarList.getValueAt(SelectedRow, 0).toString();

        carIdCombo.setSelectedItem(RegNum);
    }// GEN-LAST:event_carTableMouseClicked

    // action button responders
    // ======================================================================================================
    AllCars cars = new AllCars();
    AllCustomers customers = new AllCustomers();
    AllRentals allRentals = new AllRentals();

    private void setCustomerIdCombo() {
        ArrayList<Customer> allCustomers = customers.getAllCustomers();
        int arrSize = allCustomers.size();
        String customerIds[] = new String[arrSize];
        for (int i = 0; i < arrSize; i++) {
            customerIds[i] = allCustomers.get(i).getId();
        }
        customerIdCombo.setModel(new javax.swing.DefaultComboBoxModel<>(customerIds));
    }

    private void setCarIdCombo() {
        ArrayList<Car> availableCars = cars.getAvailableCars();
        int arrSize = availableCars.size();
        String carIds[] = new String[arrSize];
        for (int i = 0; i < arrSize; i++) {
            carIds[i] = availableCars.get(i).getId();
        }
        carIdCombo.setModel(new javax.swing.DefaultComboBoxModel<>(carIds));
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveActionPerformed
        if (cars.getAllCars().size() < 1) {
            JOptionPane.showMessageDialog(null, "No cars are available");
            return;
        }

        if (customers.getAllCustomers().size() < 1) {
            JOptionPane.showMessageDialog(null, "You have no customers");
            return;
        }

        String rentalId = UUID.randomUUID().toString();
        String carId = carIdCombo.getSelectedItem().toString();
        String customerId = customerIdCombo.getSelectedItem().toString();
        Date rentStartDate = rentalStartDate.getDate();
        Date rentEndDate = rentalEndDate.getDate();
        Date currentDate = new Date();

        if (customerId.equals("")) {
            JOptionPane.showMessageDialog(null, "Select a valid customer id");
            return;
        }
        if (carId.equals("")) {
            JOptionPane.showMessageDialog(null, "Select a valid car id");
            return;
        }
        Rental newRental = new Rental(rentalId, carId, customerId, rentStartDate,
                rentEndDate, currentDate);
        allRentals.addRental(newRental);
        cars.setCarAsRented(carId);
        addRentalDataToTable();
    }

    private void resetTextFields() {
        // rentDateTextInput.setText(t("");
    }

    private void addCarDataToTable() {
        DefaultTableModel carTableModel = (DefaultTableModel) tableCarList.getModel();

        ArrayList<Car> allCars = cars.getAllCars();
        int carArrSize = allCars.size();
        carTableModel.getDataVector().removeAllElements();
        for (int i = 0; i < carArrSize; i++) {
            Car currCar = allCars.get(i);
            if (currCar.isAvailable()) {
                String tableData[] = {currCar.getId(), currCar.getMake(), currCar.getModel(),
                    currCar.isAvailable() == true ? "Available" : "Booked",
                    String.valueOf(currCar.getPrice())};
                carTableModel.addRow(tableData);
            }
        }
    }

    private void addRentalDataToTable() {
        DefaultTableModel carsOnRentModel = (DefaultTableModel) tableCarsOnRent.getModel();

        ArrayList<Rental> rentals = allRentals.getAllRental();
        int carArrSize = rentals.size();
        carsOnRentModel.getDataVector().removeAllElements();
        for (int i = 0; i < carArrSize; i++) {
            Rental currRental = rentals.get(i);
            String tableData[] = {currRental.getRentalId(), currRental.getCarId(), currRental.getUserId(),
                currRental.getStartDate().toString(), currRental.getEndDate().toString()
            };
            carsOnRentModel.addRow(tableData);
        }
        resetTextFields();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> carIdCombo;
    private javax.swing.JLabel carRentalTitle;
    private javax.swing.JComboBox<String> customerIdCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelCustomerID;
    private javax.swing.JLabel labelRentDate;
    private javax.swing.JLabel labelRentalID1;
    private javax.swing.JLabel labelReturnDate;
    private com.toedter.calendar.JDateChooser rentalEndDate;
    private com.toedter.calendar.JDateChooser rentalStartDate;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JTable tableCarList;
    private javax.swing.JTable tableCarsOnRent;
    // End of variables declaration//GEN-END:variables
}
