package Forms;

import HelperClasses.Customer;
import java.awt.SystemColor;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author isaaxh
 */
public class AdminDashboard extends CommonFunctionality {


    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard(Customer aLoggedCustomer) {
        loggedInCustomer = aLoggedCustomer;
        initComponents();
    }

//    public AdminDashboard(Customer aLoggedUser) {
//        loggedUser = aLoggedUser;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        welcomeMessage = new javax.swing.JPanel();
        labelWelcomeMessage = new javax.swing.JLabel();
        btnCarManagement = new javax.swing.JButton();
        btnCarRental = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        editProfileBtn = new javax.swing.JButton();
        btnCustomerManagement = new javax.swing.JButton();
        salesReportBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(219, 219, 221));

        welcomeMessage.setBackground(new java.awt.Color(0, 0, 204));
        welcomeMessage.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N

        labelWelcomeMessage.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        labelWelcomeMessage.setForeground(new java.awt.Color(254, 254, 254));
        labelWelcomeMessage.setText("Welcome Admin!");

        javax.swing.GroupLayout welcomeMessageLayout = new javax.swing.GroupLayout(welcomeMessage);
        welcomeMessage.setLayout(welcomeMessageLayout);
        welcomeMessageLayout.setHorizontalGroup(
            welcomeMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeMessageLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(labelWelcomeMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        welcomeMessageLayout.setVerticalGroup(
            welcomeMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomeMessageLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(labelWelcomeMessage)
                .addGap(65, 65, 65))
        );

        btnCarManagement.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        btnCarManagement.setText("Car Management");
        btnCarManagement.setPreferredSize(new java.awt.Dimension(250, 30));
        btnCarManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarManagementActionPerformed(evt);
            }
        });

        btnCarRental.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        btnCarRental.setText("Car Rental Management");
        btnCarRental.setPreferredSize(new java.awt.Dimension(250, 30));
        btnCarRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarRentalActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(255, 0, 51));
        btnLogOut.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Log out");
        btnLogOut.setPreferredSize(new java.awt.Dimension(250, 30));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        editProfileBtn.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        editProfileBtn.setText("Edit Profile");
        editProfileBtn.setPreferredSize(new java.awt.Dimension(250, 30));
        editProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBtnActionPerformed(evt);
            }
        });

        btnCustomerManagement.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        btnCustomerManagement.setText("Customer Management");
        btnCustomerManagement.setPreferredSize(new java.awt.Dimension(250, 30));
        btnCustomerManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerManagementActionPerformed(evt);
            }
        });

        salesReportBtn.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        salesReportBtn.setText("Sales reports");
        salesReportBtn.setPreferredSize(new java.awt.Dimension(250, 30));
        salesReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesReportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(salesReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarRental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addComponent(btnCustomerManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(245, 245, 245))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(welcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarRental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salesReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnCustomerManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        changeWindow("logout", true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnCarManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarManagementActionPerformed
        changeWindow("carManagement", true);
    }//GEN-LAST:event_btnCarManagementActionPerformed

    private void btnCarRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarRentalActionPerformed
        changeWindow("adminCarRental", true);
    }//GEN-LAST:event_btnCarRentalActionPerformed

    private void btnCustomerManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerManagementActionPerformed
        changeWindow("customerManagement", true);
    }//GEN-LAST:event_btnCustomerManagementActionPerformed

    private void editProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editProfileBtnActionPerformed
        changeWindow("editProfile", true);
    }// GEN-LAST:event_editProfileBtnActionPerformed

    private void salesReportBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_salesReportBtnActionPerformed
        changeWindow("salesReport", true);
    }// GEN-LAST:event_salesReportBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoutBtnActionPerformed
    }// GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton btnCarManagement;
    private javax.swing.JButton btnCarRental;
    private javax.swing.JButton btnCustomerManagement;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton editProfileBtn;
    private javax.swing.JLabel labelWelcomeMessage;
    private javax.swing.JButton salesReportBtn;
    private javax.swing.JPanel welcomeMessage;
    // End of variables declaration//GEN-END:variables
}
