/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

/**
 *
 * @author jumpe
 */
public class RentalPage extends javax.swing.JFrame {

    /**
     * Creates new form RentalPage
     */
    public RentalPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        labelCarsOnRent = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCarsOnRent = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        labelRentalID = new javax.swing.JLabel();
        textFieldRentalID = new javax.swing.JTextField();
        labelCustomerID = new javax.swing.JLabel();
        labelRentDate = new javax.swing.JLabel();
        labelReturnDate = new javax.swing.JLabel();
        labelFees = new javax.swing.JLabel();
        textFieldFees = new javax.swing.JTextField();
        comboBoxCustomerID = new javax.swing.JComboBox<>();
        headerPanel = new javax.swing.JPanel();
        carRentalTitle = new javax.swing.JLabel();
        sidebarPanel = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        labelCarsOnRent1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableCarsOnRent1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        labelRentalID1 = new javax.swing.JLabel();
        textFieldRentalID1 = new javax.swing.JTextField();
        labelCustomerID1 = new javax.swing.JLabel();
        labelRentDate1 = new javax.swing.JLabel();
        labelReturnDate1 = new javax.swing.JLabel();
        labelFees1 = new javax.swing.JLabel();
        textFieldFees1 = new javax.swing.JTextField();
        comboBoxCustomerID1 = new javax.swing.JComboBox<>();
        headerPanel1 = new javax.swing.JPanel();
        carRentalTitle1 = new javax.swing.JLabel();
        sidebarPanel1 = new javax.swing.JPanel();
        btnLogout1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnSave1 = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();
        btnReset1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCarList1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCarList = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        labelRentalID2 = new javax.swing.JLabel();
        textFieldRentalID2 = new javax.swing.JTextField();
        labelCustomerID2 = new javax.swing.JLabel();
        labelRentDate2 = new javax.swing.JLabel();
        labelReturnDate2 = new javax.swing.JLabel();
        comboBoxCustomerID2 = new javax.swing.JComboBox<>();
        rentDateChooser = new com.toedter.calendar.JDateChooser();
        returnDateChooser = new com.toedter.calendar.JDateChooser();
        headerPanel2 = new javax.swing.JPanel();
        carRentalTitle2 = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(200, 200, 200));

        labelCarsOnRent.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        labelCarsOnRent.setForeground(new java.awt.Color(173, 12, 3));
        labelCarsOnRent.setText("Cars On Rent");

        tableCarsOnRent.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null }
                },
                new String[] {
                        "Rent ID", "Car ID", "User ID", "Rent Date", "Return Date", "Rent Fee"
                }) {
            Class[] types = new Class[] {
                    java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class,
                    java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableCarsOnRent);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addComponent(labelCarsOnRent)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3)
                                .addContainerGap()));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelCarsOnRent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel2.setBackground(new java.awt.Color(200, 200, 200));

        labelRentalID.setBackground(new java.awt.Color(255, 250, 250));
        labelRentalID.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelRentalID.setForeground(new java.awt.Color(173, 12, 3));
        labelRentalID.setText("Rental ID");

        labelCustomerID.setBackground(new java.awt.Color(255, 250, 250));
        labelCustomerID.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelCustomerID.setForeground(new java.awt.Color(173, 12, 3));
        labelCustomerID.setText("Customer ID");

        labelRentDate.setBackground(new java.awt.Color(255, 250, 250));
        labelRentDate.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelRentDate.setForeground(new java.awt.Color(173, 12, 3));
        labelRentDate.setText("Rent date");

        labelReturnDate.setBackground(new java.awt.Color(255, 250, 250));
        labelReturnDate.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelReturnDate.setForeground(new java.awt.Color(173, 12, 3));
        labelReturnDate.setText("Return date");

        labelFees.setBackground(new java.awt.Color(255, 250, 250));
        labelFees.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelFees.setForeground(new java.awt.Color(173, 12, 3));
        labelFees.setText("Fees");

        comboBoxCustomerID.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxCustomerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCustomerIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelRentalID)
                                        .addComponent(textFieldRentalID, javax.swing.GroupLayout.PREFERRED_SIZE, 85,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelCustomerID, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comboBoxCustomerID, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelRentDate)
                                .addGap(92, 92, 92)
                                .addComponent(labelReturnDate)
                                .addGap(88, 88, 88)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textFieldFees, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelFees))
                                .addContainerGap(75, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(labelFees)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldFees))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(labelRentalID)
                                                                        .addComponent(labelCustomerID)
                                                                        .addComponent(labelRentDate))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(comboBoxCustomerID)
                                                                        .addComponent(textFieldRentalID)))
                                                        .addComponent(labelReturnDate))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));

        headerPanel.setBackground(new java.awt.Color(200, 200, 200));

        carRentalTitle.setBackground(new java.awt.Color(255, 250, 250));
        carRentalTitle.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        carRentalTitle.setForeground(new java.awt.Color(173, 12, 3));
        carRentalTitle.setText("Car Rental");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(carRentalTitle)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        headerPanelLayout.setVerticalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(carRentalTitle)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        sidebarPanel.setBackground(new java.awt.Color(173, 12, 3));

        btnLogout.setText("Log Out");

        jPanel6.setBackground(new java.awt.Color(200, 200, 200));

        labelCarsOnRent1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        labelCarsOnRent1.setForeground(new java.awt.Color(173, 12, 3));
        labelCarsOnRent1.setText("Cars On Rent");

        tableCarsOnRent1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null }
                },
                new String[] {
                        "Rent ID", "Car ID", "User ID", "Rent Date", "Return Date", "Rent Fee"
                }) {
            Class[] types = new Class[] {
                    java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class,
                    java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableCarsOnRent1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addComponent(labelCarsOnRent1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane4)
                                .addContainerGap()));
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelCarsOnRent1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 138,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel7.setBackground(new java.awt.Color(200, 200, 200));

        labelRentalID1.setBackground(new java.awt.Color(255, 250, 250));
        labelRentalID1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelRentalID1.setForeground(new java.awt.Color(173, 12, 3));
        labelRentalID1.setText("Rental ID");

        labelCustomerID1.setBackground(new java.awt.Color(255, 250, 250));
        labelCustomerID1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelCustomerID1.setForeground(new java.awt.Color(173, 12, 3));
        labelCustomerID1.setText("Customer ID");

        labelRentDate1.setBackground(new java.awt.Color(255, 250, 250));
        labelRentDate1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelRentDate1.setForeground(new java.awt.Color(173, 12, 3));
        labelRentDate1.setText("Rent date");

        labelReturnDate1.setBackground(new java.awt.Color(255, 250, 250));
        labelReturnDate1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelReturnDate1.setForeground(new java.awt.Color(173, 12, 3));
        labelReturnDate1.setText("Return date");

        labelFees1.setBackground(new java.awt.Color(255, 250, 250));
        labelFees1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelFees1.setForeground(new java.awt.Color(173, 12, 3));
        labelFees1.setText("Fees");

        comboBoxCustomerID1.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxCustomerID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCustomerID1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelRentalID1)
                                        .addComponent(textFieldRentalID1, javax.swing.GroupLayout.PREFERRED_SIZE, 85,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelCustomerID1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comboBoxCustomerID1, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelRentDate1)
                                .addGap(92, 92, 92)
                                .addComponent(labelReturnDate1)
                                .addGap(88, 88, 88)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textFieldFees1, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelFees1))
                                .addContainerGap(75, Short.MAX_VALUE)));
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(labelFees1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldFees1))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGroup(jPanel7Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                                .addGroup(jPanel7Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(labelRentalID1)
                                                                        .addComponent(labelCustomerID1)
                                                                        .addComponent(labelRentDate1))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel7Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(comboBoxCustomerID1)
                                                                        .addComponent(textFieldRentalID1)))
                                                        .addComponent(labelReturnDate1))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));

        headerPanel1.setBackground(new java.awt.Color(200, 200, 200));

        carRentalTitle1.setBackground(new java.awt.Color(255, 250, 250));
        carRentalTitle1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        carRentalTitle1.setForeground(new java.awt.Color(173, 12, 3));
        carRentalTitle1.setText("Car Rental");

        javax.swing.GroupLayout headerPanel1Layout = new javax.swing.GroupLayout(headerPanel1);
        headerPanel1.setLayout(headerPanel1Layout);
        headerPanel1Layout.setHorizontalGroup(
                headerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanel1Layout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(carRentalTitle1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        headerPanel1Layout.setVerticalGroup(
                headerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(carRentalTitle1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        sidebarPanel1.setBackground(new java.awt.Color(173, 12, 3));

        btnLogout1.setText("Log Out");

        javax.swing.GroupLayout sidebarPanel1Layout = new javax.swing.GroupLayout(sidebarPanel1);
        sidebarPanel1.setLayout(sidebarPanel1Layout);
        sidebarPanel1Layout.setHorizontalGroup(
                sidebarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sidebarPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnLogout1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addContainerGap()));
        sidebarPanel1Layout.setVerticalGroup(
                sidebarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                sidebarPanel1Layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnLogout1)
                                        .addGap(22, 22, 22)));

        jPanel8.setBackground(new java.awt.Color(200, 200, 200));

        btnSave1.setText("Save");

        btnEdit1.setText("Edit");

        btnReset1.setText("Reset");
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(200, 200, 200));

        tableCarList1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tableCarList1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "Car ID", "Brand", "Model", "Status", "Price"
                }) {
            Class[] types = new Class[] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        tableCarList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableCarList1.setMaximumSize(new java.awt.Dimension(600, 72));
        tableCarList1.getTableHeader().setResizingAllowed(false);
        tableCarList1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tableCarList1);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(173, 12, 3));
        jLabel3.setText("Car List");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2)
                                .addContainerGap())
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(305, 305, 305)
                                .addComponent(jLabel3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addContainerGap(16, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSave1)
                                        .addComponent(btnEdit1)
                                        .addComponent(btnReset1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
                sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(sidebarPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(sidebarPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(sidebarPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(sidebarPanelLayout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addGroup(sidebarPanelLayout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jPanel7,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addGroup(sidebarPanelLayout.createSequentialGroup()
                                                                        .addGroup(sidebarPanelLayout
                                                                                .createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jPanel8,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)
                                                                                .addComponent(jPanel6,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE))
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                                                .addGroup(sidebarPanelLayout.createSequentialGroup()
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(headerPanel1,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addContainerGap())));
        sidebarPanelLayout.setVerticalGroup(
                sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLogout)
                                .addGap(22, 22, 22))
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(sidebarPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(sidebarPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(sidebarPanelLayout.createSequentialGroup()
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(headerPanel1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103,
                                                                Short.MAX_VALUE))
                                                .addComponent(sidebarPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addContainerGap())));

        jPanel3.setBackground(new java.awt.Color(200, 200, 200));

        btnSave.setText("Save");

        btnEdit.setText("Edit");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(200, 200, 200));

        tableCarList.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tableCarList.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "Car ID", "Brand", "Model", "Status", "Price"
                }) {
            Class[] types = new Class[] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        tableCarList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableCarList.setMaximumSize(new java.awt.Dimension(600, 72));
        tableCarList.getTableHeader().setResizingAllowed(false);
        tableCarList.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableCarList);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(173, 12, 3));
        jLabel2.setText("Car List");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1)
                                .addContainerGap())
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(305, 305, 305)
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(16, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSave)
                                        .addComponent(btnEdit)
                                        .addComponent(btnReset))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(200, 200, 200));

        labelRentalID2.setBackground(new java.awt.Color(255, 250, 250));
        labelRentalID2.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelRentalID2.setForeground(new java.awt.Color(173, 12, 3));
        labelRentalID2.setText("Rental ID");

        labelCustomerID2.setBackground(new java.awt.Color(255, 250, 250));
        labelCustomerID2.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelCustomerID2.setForeground(new java.awt.Color(173, 12, 3));
        labelCustomerID2.setText("Customer ID");

        labelRentDate2.setBackground(new java.awt.Color(255, 250, 250));
        labelRentDate2.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelRentDate2.setForeground(new java.awt.Color(173, 12, 3));
        labelRentDate2.setText("Rent date");

        labelReturnDate2.setBackground(new java.awt.Color(255, 250, 250));
        labelReturnDate2.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelReturnDate2.setForeground(new java.awt.Color(173, 12, 3));
        labelReturnDate2.setText("Return date");

        comboBoxCustomerID2.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxCustomerID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCustomerID2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelRentalID2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textFieldRentalID2, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 85,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel10Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel10Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(comboBoxCustomerID2,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 111,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel10Layout.createSequentialGroup()
                                                .addComponent(labelCustomerID2)
                                                .addGap(76, 76, 76)
                                                .addComponent(labelRentDate2)))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel10Layout.createSequentialGroup()
                                                .addGap(6, 6, 6))
                                        .addComponent(labelReturnDate2))
                                .addGap(78, 78, 78)));
        jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel10Layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(comboBoxCustomerID2))
                                        .addGroup(jPanel10Layout.createSequentialGroup()
                                                .addComponent(labelReturnDate2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelRentDate2)
                                        .addComponent(labelCustomerID2)
                                        .addComponent(labelRentalID2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textFieldRentalID2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))));

        headerPanel2.setBackground(new java.awt.Color(200, 200, 200));

        carRentalTitle2.setBackground(new java.awt.Color(255, 250, 250));
        carRentalTitle2.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        carRentalTitle2.setForeground(new java.awt.Color(173, 12, 3));
        carRentalTitle2.setText("Car Rental");

        javax.swing.GroupLayout headerPanel2Layout = new javax.swing.GroupLayout(headerPanel2);
        headerPanel2.setLayout(headerPanel2Layout);
        headerPanel2Layout.setHorizontalGroup(
                headerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanel2Layout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(carRentalTitle2)
                                .addContainerGap(330, Short.MAX_VALUE)));
        headerPanel2Layout.setVerticalGroup(
                headerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(carRentalTitle2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(headerPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(339, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(headerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(554, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxCustomerIDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboBoxCustomerIDActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_comboBoxCustomerIDActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnResetActionPerformed

    private void comboBoxCustomerID1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboBoxCustomerID1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_comboBoxCustomerID1ActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnReset1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnReset1ActionPerformed

    private void comboBoxCustomerID2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboBoxCustomerID2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_comboBoxCustomerID2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentalPage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentalPage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentalPage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentalPage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentalPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave1;
    private javax.swing.JLabel carRentalTitle;
    private javax.swing.JLabel carRentalTitle1;
    private javax.swing.JLabel carRentalTitle2;
    private javax.swing.JComboBox<String> comboBoxCustomerID;
    private javax.swing.JComboBox<String> comboBoxCustomerID1;
    private javax.swing.JComboBox<String> comboBoxCustomerID2;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel headerPanel1;
    private javax.swing.JPanel headerPanel2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelCarsOnRent;
    private javax.swing.JLabel labelCarsOnRent1;
    private javax.swing.JLabel labelCustomerID;
    private javax.swing.JLabel labelCustomerID1;
    private javax.swing.JLabel labelCustomerID2;
    private javax.swing.JLabel labelFees;
    private javax.swing.JLabel labelFees1;
    private javax.swing.JLabel labelRentDate;
    private javax.swing.JLabel labelRentDate1;
    private javax.swing.JLabel labelRentDate2;
    private javax.swing.JLabel labelRentalID;
    private javax.swing.JLabel labelRentalID1;
    private javax.swing.JLabel labelRentalID2;
    private javax.swing.JLabel labelReturnDate;
    private javax.swing.JLabel labelReturnDate1;
    private javax.swing.JLabel labelReturnDate2;
    private com.toedter.calendar.JDateChooser rentDateChooser;
    private com.toedter.calendar.JDateChooser returnDateChooser;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel sidebarPanel1;
    private javax.swing.JTable tableCarList;
    private javax.swing.JTable tableCarList1;
    private javax.swing.JTable tableCarsOnRent;
    private javax.swing.JTable tableCarsOnRent1;
    private javax.swing.JTextField textFieldFees;
    private javax.swing.JTextField textFieldFees1;
    private javax.swing.JTextField textFieldRentalID;
    private javax.swing.JTextField textFieldRentalID1;
    private javax.swing.JTextField textFieldRentalID2;
    // End of variables declaration//GEN-END:variables
}
